In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

df=pd.read_csv("drug200.csv")

df.head()
df.info()
df.describe()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

Age              int64
Sex             object
BP              object
Cholesterol     object
Na_to_K        float64
Drug            object
dtype: object

In [2]:
df.head()
df.tail()

     Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [3]:
print(df.isnull().sum())

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [4]:
df=pd.get_dummies(df,columns=["Age","Sex","BP","Cholesterol"])

In [5]:
df.drop(columns=["Na_to_K"])

,Drug,Age_15,Age_16,Age_17,Age_18,Age_19,Age_20,Age_21,Age_22,Age_23,...,Age_72,Age_73,Age_74,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL
0,drugY,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,True,False,False,True,False
1,drugC,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,True,False
2,drugC,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,True,False
3,drugX,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,True,False
4,drugY,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,drugC,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,True,False
196,drugC,False,True,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,True,False
197,drugX,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,True,False
198,drugX,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,True,False,True
199,drugX,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True

In [8]:
X=df.drop(columns=["Drug"])
y=df["Drug"]

In [9]:
X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=42,test_size=0.2)

In [10]:
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [11]:
dt=DecisionTreeClassifier()
dt.fit(X,y)

DecisionTreeClassifier()

In [12]:
y_pred=dt.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(classification_report(y_test,y_pred))
print(cm)

              precision    recall  f1-score   support

       drugA       0.40      1.00      0.57         6
       drugB       0.00      0.00      0.00         3
       drugC       0.83      1.00      0.91         5
       drugX       0.58      1.00      0.73        11
       drugY       0.00      0.00      0.00        15

    accuracy                           0.55        40
   macro avg       0.36      0.60      0.44        40
weighted avg       0.32      0.55      0.40        40

[[ 6  0  0  0  0]
 [ 3  0  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 6  0  1  8  0]]

C:\Users\Hrishikesh Kali\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\Hrishikesh Kali\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Hrishikesh Kali\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Hrishikesh Kali\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [13]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,y_train)
y_pred2=svc.predict(X_test)

print(classification_report(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))

              precision    recall  f1-score   support

       drugA       1.00      0.17      0.29         6
       drugB       0.00      0.00      0.00         3
       drugC       1.00      0.20      0.33         5
       drugX       0.43      0.27      0.33        11
       drugY       0.47      0.93      0.62        15

    accuracy                           0.47        40
   macro avg       0.58      0.31      0.31        40
weighted avg       0.57      0.47      0.41        40

0.475

In [16]:
kfol=KFold(random_state=42,shuffle=True,n_splits=5)
cv_score=cross_val_score(DecisionTreeClassifier(),X,y,cv=kfol,scoring="accuracy")
print(cv_score)

[0.9   0.925 0.825 0.925 0.95 ]